version: '3.4'

services:
  cadastroapi:
    image: ${DOCKER_REGISTRY-}cadastroapi
    build:
      context: .
      dockerfile: CadastroAPI/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=cadastroDb;User=erick;Password=erick
    networks:
      - my_net

  db:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cadastroDb
      - MYSQL_USER=erick
      - MYSQL_PASSWORD=erick
    volumes:
      - my_db:/var/lib/mysql
      - ./dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - my_net


volumes:
 my_db:

networks:
 my_net: